CREATE TABLE receipts (
    receipt_number TEXT PRIMARY KEY,
    note TEXT,
    receipt_type TEXT,
    refund_for TEXT,
    order_info TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    source TEXT,
    receipt_date TIMESTAMP,
    cancelled_at TIMESTAMP,
    total_money NUMERIC,
    total_tax NUMERIC,
    points_earned NUMERIC,
    points_deducted NUMERIC,
    points_balance NUMERIC,
    customer_id TEXT,
    total_discount NUMERIC,
    employee_id UUID,
    store_id UUID,
    pos_device_id UUID,
    dining_option TEXT,
    tip NUMERIC,
    surcharge NUMERIC
);